<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-04-12T16:37:46 MDT" name="Default suite" finished-at="2023-04-12T16:38:09 MDT" duration-ms="22811">
    <groups>
    </groups>
    <test started-at="2023-04-12T16:37:46 MDT" name="Default test" finished-at="2023-04-12T16:38:09 MDT" duration-ms="22811">
      <class name="assessment.AssessmentTests">
        <test-method signature="createAccount_Account_Already_Exists()[pri:0, instance:assessment.AssessmentTests@c03cf28]" started-at="2023-04-12T16:37:46 MDT" name="createAccount_Account_Already_Exists" finished-at="2023-04-12T16:37:53 MDT" duration-ms="6542" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createAccount_Account_Already_Exists -->
        <test-method signature="createAccount_Account_Does_Not_Exist_Yet()[pri:0, instance:assessment.AssessmentTests@c03cf28]" started-at="2023-04-12T16:37:53 MDT" name="createAccount_Account_Does_Not_Exist_Yet" finished-at="2023-04-12T16:37:57 MDT" duration-ms="4402" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Sign up successful.] but found [This user already exist.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Sign up successful.] but found [This user already exist.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at assessment.AssessmentTests.createAccount_Account_Does_Not_Exist_Yet(AssessmentTests.java:99)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createAccount_Account_Does_Not_Exist_Yet -->
        <test-method signature="logIn()[pri:0, instance:assessment.AssessmentTests@c03cf28]" started-at="2023-04-12T16:37:57 MDT" name="logIn" finished-at="2023-04-12T16:38:03 MDT" duration-ms="5979" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logIn -->
        <test-method signature="logOut()[pri:0, instance:assessment.AssessmentTests@c03cf28]" started-at="2023-04-12T16:38:03 MDT" name="logOut" finished-at="2023-04-12T16:38:09 MDT" duration-ms="5829" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOut -->
      </class> <!-- assessment.AssessmentTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
